/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure

  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  docs: [

    'README',

    {
      type: 'category',
      label: 'What Is MatrixETF',
      link: {
      type: 'generated-index',
    },
      collapsed: false,
      items: [
         'What Is MatrixETF/Introduction',
         'What Is MatrixETF/MatrixETF',
         'What Is MatrixETF/Vison',
         'What Is MatrixETF/Roadmap',
         'What Is MatrixETF/MatrixETF FAQ'
  ],
    },

  'Audit Report',

  {
      type: 'category',
      label: 'Products',
      link: {
      type: 'generated-index',
    },
      collapsed: false,
      items: [
         'Products/The Logical Design of MatrixETF',
         'Products/Matrix Index',
         'Products/Matrix Swap',
         'Products/Matrix Derivatives',
         'Products/Farming & Pool',
         'Products/MatrixETF Set',
         'Products/Matrix Blind Box'
  ],
    },

{
      type: 'category',
      label: 'Community Ecology',
      link: {
      type: 'generated-index',
    },
      collapsed: false,
      items: [

         {
          type: 'category',
          label: 'MatrixETF Community Ambassador Plan',
          link: {
            type: 'doc',
            id: 'Community Ecology/MatrixETF-Community-Ambassador-Plan/README',
          },
          items: [
            'Community Ecology/MatrixETF-Community-Ambassador-Plan/How to be a MatrixETF Community Ambassador',
            'Community Ecology/MatrixETF-Community-Ambassador-Plan/Community Ambassador Point and Level',
            'Community Ecology/MatrixETF-Community-Ambassador-Plan/Ambassador FAQ',
          ],
        },

         'Community Ecology/Community Links',
         'Community Ecology/Brand suite',
         'Community Ecology/Investors & Partner',
  ],
    },

  ],
   
};

module.exports = sidebars;
